=== DickvdBrink/SchemaStore/src/schemas/json/epr-manifest.json
{
	"title": "JSON schema for Entry Point Regulation manifest files",
	"$schema": "http://json-schema.org/draft-04/schema#",

	"type": "object",
	"required": [ "rules" ],

	"definitions": {
		"behaviors": {
			"type": "string",
			"enum": [ "block" ]
		},
		"rule": {
			"type": "object",
			"properties": {
				"path": {
					"description": "Relative path to resource.",
					"type": "string"
				},
				"regex": {
					"description": "A regular expression for identifying paths to resources.",
					"type": "string"
				},
				"types": {
					"type": "array",
					"items": {
						"type": "string",
						"enum": [ "navigation", "image" ]
					}
				},
				"allowData": {
					"description": "Determines if data is allowed at this path.",
					"type": "boolean"
				}
			}
		}
	},

	"properties": {
		"site": {
			"description": "A fully qualified URL of your website.",
			"type": "string",
			"format": "uri"
		},
		"maxAge": {
			"description": "Set the max age HTTP cache expiration.",
			"type": "integer"
		},
		"reportUrl": {
			"type": "string",
			"format": "uri"
		},
		"defaultNavBehavior": {
			"$ref": "#/definitions/behaviors"
		},
		"defaultResBehavior": {
			"$ref": "#/definitions/behaviors"
		},
		"rules": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/rule"
			}
		}
	}
}

=== DickvdBrink/SchemaStore/src/test/epr-manifest/official-example.json
{
	"site": "https://[Your EPR-enabled website]",
	"maxAge": 31536000,
	"reportUrl": "https://[Report URL]",
	"defaultNavBehavior": "block",
	"defaultResBehavior": "block",
	"rules": [
		{ "path": "/", "types": [ "navigation" ], "allowData": false },
		{ "regex": "^/\\d+$", "types": [ "navigation" ], "allowData": false },
		{ "path": "/image", "types": [ "image" ], "allowData": true },
		{ "regex": "^/(scoreboard|random|favorites|recentvisits|create)$", "types": [ "navigation" ], "allowData": false },
		{ "regex": "^/(recent|popular|metrics|template|search)$", "types": [ "navigation" ], "allowData": true }
	]
}
